### ISSUE TITLE
Adding order functionality

### ISSUE THREAD

**Issue by uzarra** [DotNetNomads/NextApi#16]
Extending the [paged request](https://github.com/DotNetNomads/NextApi/blob/master/src/base/NextApi.Common/Paged/PagedRequest.cs), so that users can set the order of the returned data.

Usage example:
```
var paged = new PagedRequest
{
    Orders = new [] 
    {
        new Order( OrderOperators.OrderBy, "propertyName0"),
        new Order( OrderOperators.ThenByDescending, "propertyName1"),
    }
};
```

**Comment by binali-rustamov** [comment]
These changes will be available in the following versions of packages:
 - NextApi.Common/1.0.2
 - NextApi.Server.Common/1.0.2
 - NextApi.Server/1.0.2

How to update?
 - Client-side: Update or install NextApi.Common package with version 1.0.2.
 - Server-side: Update NextApi.Server package to 1.0.2.

@uzarra, thank you for this functionality and notes about usage. 
We'll add it in the documentation :)
