### ISSUE TITLE
NextApiAccessor Integer SubjectId

### ISSUE THREAD

**Issue by lordofffarm** [DotNetNomads/NextApi#18]
В разных системах идентификатор пользователя может иметь тип отличающийся от `int`. Например, в Keycloak это UUID. Предлагается вместо `int` возвращать `string`, т. к. SubjectId из токена выходит в виде строки.  
Так же, раз подразумевается что типы идентификаторов могут быть разные, предлагается сделать ILoggedEntity generic. #17

**Comment by binali-rustamov** [comment]
Thanks for implementation

**Comment by binali-rustamov** [comment]
Those changes are available in version 1.0.3 of following packages:
- NextApi.Common
- NextApi.Server
- NextApi.Server.EfCore.DAL
- NextApi.Server.Common
